
services:
  spring-app:
    image: endermaru/22-5-team1-server:latest
    container_name: spring-app-container
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DOC_SWAGGER_UI_ENABLED: "true"
      SPRING_DOC_SWAGGER_UI_PATH: "/swagger-ui"
      SPRING_DOC_API_DOCS_ENABLED: "true"
      SPRING_DOC_API_DOCS_PATH: "/v3/api-docs"
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - .env:/app/.env # 로컬의 .env 파일을 컨테이너로 마운트

networks:
  app-network:
    driver: bridge