services:
  spring-app:
    # 이미지를 docker hub pull
    image: endermaru/22-5-team1-server:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
