# 개발용
services:
  spring-app:
    # 빌드(DockerFile)
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: local
  redis:
    # 데이터 저장 비활성화
    volumes: []
    command: ["redis-server", "--save", ""]
volumes:
  redis-data: null

