services:
  spring-app:
    # 이미지를 docker hub pull
    image: endermaru/22-5-team1-server:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env

networks:
  app-network:
    driver: bridge