# 개발용
services:
  spring-app:
    # 빌드(DockerFile)
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

