spring:
    application:
        name: team1server
    jpa:
        properties:
            hibernate:
                jdbc:
                    timezone: Asia/Seoul
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                        - https://www.googleapis.com/auth/userinfo.email
                        - https://www.googleapis.com/auth/userinfo.profile
                        - openid
                provider:
                    google:
                        authorization-uri: ${GOOGLE_AUTH_URI}
                        token-uri: ${GOOGLE_TOKEN_URI}
                        user-name-attribute: email
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_SRC}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: ${SPRING_REDIS_HOST:localhost}
            port: ${SPRING_REDIS_PORT:6379}
custom:
    domain-url: api.survey-josha.site
    is-secure: ${IS_SECURE:false}
    SECRET: ${SECRET:Helloworld}

springdoc:
    swagger-ui:
        enabled: ${SPRING_DOC_SWAGGER_UI_ENABLED:true}
        path: ${SPRING_DOC_SWAGGER_UI_PATH:/swagger-ui}
    api-docs:
        enabled: ${SPRING_DOC_API_DOCS_ENABLED:true}
        path: ${SPRING_DOC_API_DOCS_PATH:/v3/api-docs}
        server-base-url: https://api.survey-josha.site # HTTPS 기본 URL 설정

amazon:
    aws:
        accessKey: ${S3ACCESSKEY:""}
        secretKey: ${S3SECRETKEY:""}
        region: ${S3REGION:""}
        bucketPublic: ${S3BUCKETPUBLIC:""}
        bucketPrivate: ${S3BUCKETPRIVATE:""}
        bucketPrivateKey: ${S3_BUCKET_PRIVATE_KEY:""}
