spring:
    application:
        name: internhasha
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    timezone: Asia/Seoul
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_SRC:""}
        password: ${EMAIL_PASSWORD:""}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: redis
            port: 6379

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui
    api-docs:
        enabled: true
        path: /v3/api-docs

amazon:
    aws:
        accessKey: ${S3_ACCESS_KEY:""}
        secretKey: ${S3_SECRET_KEY:""}
        region: ${S3REGION:""}
        bucketPublic: ${S3_BUCKET_PUBLIC:""}
        bucketPrivate: ${S3_BUCKET_PRIVATE:""}

cloudfront:
    keyPairId: ${CLOUDFRONT_KEYPAIR_ID:""}
    privateKeyText: ${CLOUDFRONT_PRIVATE_KEY:""}

management:
    endpoint:
        health:
            access: read_only
            probes:
                enabled: true
            show-details: never
            group:
              startup:
                  include:
                      - livenessState
    endpoints:
        web:
            exposure:
                include: health

server:
    port: 8080

custom:
    DEV_SECRET: ${SECRET_FOR_INTERNHASHA:"Hello world"}
    TOKEN_PRIVATE_KEY: ${TOKEN_PRIVATE_KEY:"veryLongLongKeyForSecretKeyGeneration"}

    domain-name: localhost:8080
    protocol: http
    is-secure: false

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: ${DEV_DATASOURCE_URL:""}
        username: ${PROD_DATASOURCE_USERNAME:""}
        password: ${PROD_DATASOURCE_PASSWORD:""}
    data:
        redis:
            host: ${REDIS_URL:""}
            port: 6379

server:
    port: 8081

custom:
    domain-name: dev-internhasha.wafflestudio.com
    protocol: https
    is-secure: true
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: ${PROD_DATASOURCE_URL:""}
        username: ${PROD_DATASOURCE_USERNAME:""}
        password: ${PROD_DATASOURCE_PASSWORD:""}

    data:
        redis:
            host: ${REDIS_URL:""}
            port: 6379

custom:
    domain-name: internhasha.wafflestudio.com
    protocol: https
    is-secure: true

server:
    port: 8080
