spring:
    application:
        name: internhasha
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    timezone: Asia/Seoul
    mail:
        host: smtp.gmail.com
        port: 587
        username: internhasha.official@gmail.com
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: redis
            port: 6379

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui
    api-docs:
        enabled: true
        path: /v3/api-docs

amazon:
    aws:
        accessKey: ""
        secretKey: ""
        region: ""
        bucketPublic: ""
        bucketPrivate: ""

cloudfront:
    keyPairId: ""
    privateKeyText: ""

management:
    endpoint:
        health:
            access: read_only
            probes:
                enabled: true
            show-details: never
            group:
                startup:
                    include:
                        - livenessState
    endpoints:
        web:
            exposure:
                include: health

server:
    port: 8080

auth:
    redis:
        prefix: internhasha:local

custom:
    DEV_SECRET: "Hello world"
    TOKEN_PRIVATE_KEY: "veryLongLongKeyForSecretKeyGeneration"

    domain-name: localhost:8080
    protocol: http
    is-secure: false

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
    mail:
        password: ""
---
secret-names: dev/internhasha

spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url:
        username:
        password:
    data:
        redis:
            host:
            port: 6379
            database: 4
    mail:
        password:

amazon:
    aws:
        accessKey:
        secretKey:
        region:
        bucketPublic:
        bucketPrivate:

cloudfront:
    keyPairId:
    privateKeyText:

auth:
    redis:
        prefix: internhasha:dev

custom:
    DEV_SECRET:
    TOKEN_PRIVATE_KEY:

    domain-name: dev-internhasha.wafflestudio.com
    protocol: https
    is-secure: true
---
secret-names: prod/internhasha

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url:
        username:
        password:

    data:
        redis:
            host:
            port: 6379
            database: 4
    mail:
        password:

amazon:
    aws:
        accessKey:
        secretKey:
        region:
        bucketPublic:
        bucketPrivate:

cloudfront:
    keyPairId:
    privateKeyText:

auth:
    redis:
        prefix: internhasha:prod

custom:
    DEV_SECRET:
    TOKEN_PRIVATE_KEY:

    domain-name: internhasha.wafflestudio.com
    protocol: https
    is-secure: true
